# Generated by Django 3.2.6 on 2021-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=80, verbose_name='vendor')),
                ('soft_name', models.CharField(max_length=60, verbose_name='soft_name')),
                ('dep', models.CharField(max_length=60, verbose_name='dep')),
                ('pur_num', models.IntegerField(verbose_name='pur_num')),
                ('autho_type', models.CharField(choices=[('0', '永久授权'), ('1', '非永久授权')], max_length=100, verbose_name='autho_type')),
                ('pur_date', models.DateField(verbose_name='pur_date')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='expired_date')),
            ],
        ),
    ]
