# Generated by Django 3.2.6 on 2021-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='demander',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='demander'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='dep',
            field=models.CharField(max_length=60, verbose_name='预算部门'),
        ),
    ]
